export const mail = {
  content: [
    {
      m_id: "1234",
      m_type: "寄件人：",
      m_title: "hihi hiffffffffffffffffffffffffffffffffffff",
      m_content: "1234567",
      m_time: "12月02日 10:25",
      m_uid: 301322,
      m_uname: "AAA",
      m_isNew: false,
    },
    {
      m_id: "1235",
      m_type: "寄件人：",
      m_title: "11111111133f",
      m_content: "jjjjjjjjjjjjjj",
      m_time: "12月03日 11:25",
      m_uid: 301323,
      m_uname: "BBB",
      m_isNew: false,
    },
    {
      m_id: "1236",
      m_type: "寄件人：",
      m_title: "哈囉",
      m_content: "hihihihihihi",
      m_time: "12月03日 11:33",
      m_uid: 301323,
      m_uname: "CCC",
      m_isNew: true,
    },
  ],
};

export const comment = {
  content: [
    {
      m_id: "1234",
      m_type: "Re：",
      m_content: "hello!!!",
      m_time: "12月02日 10:35",
      m_uid: 301323,
      m_uname: "BBB",
      m_isNew: false,
    },
    {
      m_id: "1234",
      m_type: "Re：",
      m_content: "你好！",
      m_time: "12月03日 11:25",
      m_uid: 301323,
      m_uname: "BBB",
      m_isNew: false,
    },
    {
      m_id: "1234",
      m_type: "Re：",
      m_content: "OK",
      m_time: "12月03日 11:33",
      m_uid: 301322,
      m_uname: "AAA",
      m_isNew: false,
    },
    {
      m_id: "1235",
      m_type: "Re：",
      m_content: "OKKKK",
      m_time: "12月03日 12:33",
      m_uid: 301323,
      m_uname: "BBB",
      m_isNew: false,
    },
  ],
};
