import "./globals.css";
import "@wanin/ui/styles.css";
import {
  ErrorBoundary,
  MainNav,
  GeistProvider,
  NextAuthSession,
} from "@/components/client";
import { ThemeProvider } from "@/lib/next-themes";
import { getBaseUrl } from "@/utils/get-base-url";
import type { Session } from "next-auth";
import { headers } from "next/headers";
import { type ReactNode } from "react";

const getSession = async (cookie: string): Promise<Session> => {
  const response = await fetch(`${getBaseUrl()}/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const session = await getSession(headers().get("cookie") ?? "");
  return (
    <html lang="en">
      <head>
        <title>League Funny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ErrorBoundary>
          <NextAuthSession session={session}>
            <ThemeProvider enableSystem={true} attribute="class">
              <GeistProvider>
                <MainNav />
                {children}
              </GeistProvider>
            </ThemeProvider>
          </NextAuthSession>
        </ErrorBoundary>
      </body>
    </html>
  );
};

export default RootLayout;
