import "./globals.css";
import "@wanin/ui/styles.css";
import { ErrorBoundary, MainNav, Provider } from "@/components/client";
import { type Session, unstable_getServerSession } from "next-auth";
import { type ReactNode } from "react";

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const session = await unstable_getServerSession();
  return (
    <html lang="en">
      <head>
        <title>League Funny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="w-bg-primary scrollbar-thin scrollbar-thumb-gray-400 dark:scrollbar-thumb-primary scrollbar-thumb-rounded-full">
        <ErrorBoundary>
          <Provider session={session as Session}>
            <MainNav />
            {children}
          </Provider>
        </ErrorBoundary>
      </body>
    </html>
  );
};

export default RootLayout;
