name: Web CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ apps/web, develop ]
#    types: [opened, synchronize]

env:
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  FACEBOOK_ID: ${{ secrets.FACEBOOK_ID }}
  FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
  TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
  TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
  API_URL: ${{ secrets.API_URL }}
  PNPM_VERSION: 6.32.2
  NODE_VERSION: 18.*

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      FACEBOOK_ID: ${{ secrets.FACEBOOK_ID }}
      FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      API_URL: ${{ secrets.API_URL }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    strategy:
      matrix:
        node: 18.*

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: cd ../.. && pnpm build --filter web...

      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/web/.next
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: ESLint
        run: pnpm lint --filter web...

      - name: Unit tests
        run: pnpm test --filter web.

  e2e-on-chrome:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ${{ github.workspace }}/apps/web/.next
          key: |
            ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - uses: cypress-io/github-action@v4
        env:
          NEXTAUTH_SECRET: ${{ env.NEXTAUTH_SECRET }}
          FACEBOOK_ID: ${{ env.FACEBOOK_ID }}
          FACEBOOK_SECRET: ${{ env.FACEBOOK_SECRET }}
          TWITCH_CLIENT_ID: ${{ env.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ env.TWITCH_CLIENT_SECRET }}
          API_URL: ${{ env.API_URL }}
        with:
          start: pnpm start --filter web...
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          command: pnpm e2e:chrome --filter web
